services: 
  vector-fusion:
    build: .
    command: python3 run_painterly_render.py -c vectorfusion.yaml -pt "${PROMPT}" -save_step 10 -respath /tmp/workdir -d 8888 --download
    volumes:
      - ./VectorFusion-pytorch:/VectorFusion-pytorch
      - ./tmp:/tmp/workdir