services:
  vector-fusion:
    container_name: ${CONTAINER_NAME}
    build: .
    command: ["bash", "/VectorFusion-pytorch/start.sh"]
    volumes:
      - ./VectorFusion-pytorch:/VectorFusion-pytorch
      - ./DiffSketcher:/DiffSketcher
      - ./assets:/assets
      - ./tmp:/tmp/workdir
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}
      WANDB_ENTITY: ${WANDB_ENTITY}
      WANDB_PROJECT: ${WANDB_PROJECT}
      WANDB_NAME: ${WANDB_NAME}
      WANDB_RUN_GROUP: ${WANDB_RUN_GROUP}
      WANDB_TAGS: ${WANDB_TAGS}
      PROMPT: ${PROMPT}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "${GPU_ID}" ]
              capabilities: [ gpu ]