services:
  vector-fusion:
    container_name: ${CONTAINER_NAME}
    build: .
    command: python3 run_painterly_render.py -c vectorfusion.yaml -update="${PARAMS}" -pt "${PROMPT}" -save_step 10 -respath /tmp/workdir -d 8888 --download --use_wandb --log_clip --log_image
    volumes:
      - ./VectorFusion-pytorch:/VectorFusion-pytorch
      - ./DiffSketcher:/DiffSketcher
      - ./assets:/assets
      - ./tmp:/tmp/workdir
      - ./testdata:/testdata
    environment:
      WANDB_API_KEY: ${WANDB_API_KEY}
      WANDB_ENTITY: ${WANDB_ENTITY}
      WANDB_PROJECT: ${WANDB_PROJECT}
      WANDB_NAME: ${WANDB_NAME}
      WANDB_RUN_GROUP: ${WANDB_RUN_GROUP}
      WANDB_TAGS: ${WANDB_TAGS}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "${GPU_ID}" ]
              capabilities: [ gpu ]
